### ISSUE TITLE
Use virtual methods

### ISSUE THREAD

**Issue by ghost** [dorothysyu/part2#9]
It's good practice if someone wants to build off of your class.

**Comment by dorothysyu** [comment]
Which class is this talking about? Is this still an issue with the updated code?

**Comment by ghost** [comment]
This was raised assuming that you would use wrappers. However, since you choose to subclass Array there are some unnecessary methods that are passed unless you give them an empty method.

For example, your Array has 
    // The value at the given index will now be the given obj.
    // Does nothin the string if the given index is out of bounds of the array.
    virtual void put(int idx, Object* obj);
but your Int_Array has 
    // The value at the given index will now be the given int.
    // Does nothin the string if the given index is out of bounds of the array.
    void put(int idx, int i) {
These are considered two separate methods and Array requires Int_Array to implement these methods because it is virtual.

**Comment by ghost** [comment]
Also, you forgot to make 
    // Returns the element at the given index.
    // Terminates the program if given index is out of bounds.
    Object* at(int i);
this virtual.

**Comment by dorothysyu** [comment]
You're right - those are two separate methods. For `put(int i, ??? value)`, the type for the parameter for value will always be different depending on the type - so it doesn't make sense for that function to be virtual (which ideally, we'd be able to promise to the user in the array class that there will be a put method, but lack of generics makes this difficult). Same issue for at(), since the return type will be different (since we aren't wrapping int/bools/floats in object wrappers). I will delete these methods from the Array interface and keep them in the subclasses

**Comment by dorothysyu** [comment]
pushed
